Repository Ctoic/CalHub, pull requests merged in 2023-10, with the labels that each got.

#21 added function to change bg color when user calculates expression
  script.js
  style.css
Labels: hactoberfest

#44 Improved UI/UX
  style.css
Labels: hactoberfest, hactoberfest-accepted

#49 Working in exponent bug
  script.js
Labels: hacktoberfest, hacktoberfest-accepted

#68 corrected the square root bug
  index.html
  script.js
Labels: hacktoberfest, hacktoberfest-accepted
